version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 6.0
  build:
    commands:
      - cd Todolendar.API
      - dotnet restore
      - dotnet build -c Release
      - dotnet publish -c Release -r linux-x64 -o ./publish
artifacts:
  files:
    - ./appspec.yml
    - ./scripts/*
    - ./Todolendar.API/publish/**/*
